doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                year:  App\Doctrine\YearFunction
                month: App\Doctrine\MonthFunction
            numeric_functions:
                st_contains:   CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                contains:      CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                st_area:       CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Area
                geomfromtext:  CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                st_intersects: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                st_buffer:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STBuffer
                point:         CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
