# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        name: twyne
        handler_id: session.handler.native_file
        storage_factory_id: session.storage.factory.native
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400

    php_errors:
        log: true
