name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '**'

jobs:
  build:

    services:
      db:
        image: ${{ matrix.db }}
        env:
          MYSQL_DATABASE: twyne_test
          MYSQL_ROOT_PASSWORD: testpwd
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=10s --health-retries=3 --health-start-period=30s

    strategy:
      matrix:
        # PHP: https://www.php.net/supported-versions.php
        # MariaDB: https://mariadb.org/download
        # MySQL: https://dev.mysql.com/downloads/mysql/
        include:
          # Minimum supported versions
          - php: '8.2'
            db: 'mariadb:10.6.28'
            server_version: 'mariadb-10.6.28'
          # Current stable versions
          - php: '8.3'
            db: 'mariadb:11.4.12'
            server_version: 'mariadb-11.4.12'
          # Forward compatibility
          - php: '8.4'
            db: 'mysql:9.1'
            server_version: '9.1'
          # Old PHP with new DB
          - php: '8.2'
            db: 'mysql:9.1'
            server_version: '9.1'
          # New PHP with old DB
          - php: '8.4'
            db: 'mariadb:10.6.28'
            server_version: '10.6.28'

    runs-on: 'ubuntu-latest'

    name: PHP ${{ matrix.php }}, ${{ matrix.db }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        extensions: fileinfo, json, pdo, mysql, pdo_mysql, mbstring

    - name: Install
      env:
        APP_ENV: test
      run: |
        export DATABASE_URL="mysql://root:testpwd@127.0.0.1:3306/twyne_test?serverVersion=${{ matrix.db }}"
        echo DATABASE_URL is: $DATABASE_URL
        echo DATABASE_URL=$DATABASE_URL > .env.test.local
        sudo apt-get update -q
        sudo apt-get --fix-broken install
        sudo apt-get install -y exiftool shellcheck
        composer install
        ./bin/console doctrine:migrations:migrate
        npm ci

    - name: Test
      run: |
        composer test
        npm run test
        shellcheck bin/deploy.sh

    - name: Build and check assets
      run: |
        npm run build
        git diff
        git status | grep "nothing to commit, working tree clean"
